name: Fetch SUL Events RSS Feed

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  fetch_rss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch Library Events RSS Feed
        run: |
          wget -O sul-events-feed.rss.xml "https://events.stanford.edu/widget/view?schools=stanford&departments=stanford_university_libraries&days=90&num=50&html_descriptions=1&hide_past=1&format=rss"
          git config user.email "simonjwiles@gmail.com"
          git config user.name "Simon Wiles"
          git add .
          if ! git diff --exit-code --quiet HEAD --; then
            git commit -m "Update RSS feed at $(date +"%Y-%m-%d %H:%M:%S %Z")"
            git push
          fi
